export const routes = {
  storefront: {
    home: "/",
    blog: "/blog",
    blogPost: (slug: string) => `/blog/${slug}`,
    categories: "/categories",
    category: (slug: string) => `/categories/${slug}`,
    preview: "/preview",
    product: (categorySlug: string, productSlug: string) => `/categories/${categorySlug}/${productSlug}`,
    deals: "/deals",
    deal: (slug: string) => `/deals/${slug}`,
    occasions: "/occasions",
    occasion: (slug: string) => `/occasions/${slug}`,
    account: "/account",
    accountProfile: "/account/profile",
    accountAddresses: "/account/addresses",
    accountOrders: "/account/orders",
    accountOrderDetail: (orderNumber: string) => `/account/orders/${orderNumber}`,
    accountReviews: "/account/reviews",
    wishlist: "/wishlist",
    cart: "/cart",
    checkout: "/checkout",
    checkoutConfirmation: (orderNumber: string) => `/checkout/confirmation/${orderNumber}`,
    orderInvoice: (orderNumber: string) => `/api/orders/${orderNumber}/invoice`,
    about: "/about",
    contact: "/contact",
    privacy: "/privacy",
    terms: "/terms",
    shippingPolicy: "/shipping-policy",
    returnPolicy: "/return-policy",
  },
  admin: {
    dashboard: "/admin",
    homepage: "/admin/homepage",
    homepageSections: "/admin/homepage/sections",
    homepageBanners: "/admin/homepage/banners",
    homepageCampaigns: "/admin/homepage/campaigns",
    products: "/admin/products",
    productCreate: "/admin/products/new",
    productEdit: (productId: string) => `/admin/products/${productId}/edit`,
    deals: "/admin/deals",
    dealCreate: "/admin/deals/new",
    dealEdit: (dealId: string) => `/admin/deals/${dealId}/edit`,
    blog: "/admin/blog",
    blogEdit: (postId: string) => `/admin/blog/${postId}/edit`,
    reviews: "/admin/reviews",
    categories: "/admin/categories",
    categoryEdit: (categoryId: string) => `/admin/categories/${categoryId}/edit`,
    occasions: "/admin/occasions",
    occasionCreate: "/admin/occasions/new",
    occasionEdit: (occasionId: string) => `/admin/occasions/${occasionId}/edit`,
    orders: "/admin/orders",
    orderDetail: (orderNumber: string) => `/admin/orders/${orderNumber}`,
    revenue: "/admin/revenue",
    inventory: "/admin/inventory",
    activity: "/admin/activity",
    settings: "/admin/settings",
  },
  auth: {
    signIn: "/auth/sign-in",
    signUp: "/auth/sign-up",
    error: "/auth/error",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/auth/verify-email",
  },
  system: {
    unauthorized: "/unauthorized",
    forbidden: "/forbidden",
  },
  docs: {
    architecture: "/docs/architecture",
  },
} as const;
